name: Pnpm

description: Install pnpm

inputs:
  architecture:
    description: The architecture to use
    required: false
  cpu:
    description: The cpu architecture to use
    required: false

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6.0.4

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version-file: .node-version
        architecture: ${{ inputs.architecture }}
        cache: pnpm

    - if: ${{ inputs.cpu }}
      shell: bash
      run: pnpm config set supportedArchitectures.cpu "${CPU_ARCH}"
      env:
        CPU_ARCH: ${{ inputs.cpu }}

    - name: pnpm
      shell: bash
      run: |
        corepack enable
        pnpm install

    - name: yarn pnp
      shell: bash
      run: |
        cd fixtures/pnp
        yarn install

        cd ../global-pnp
        yarn install

        cd ../yarn
        yarn install
